<div class="main-container">
	<div class="container-inner">
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('corporate_about')->toHtml(); ?>
	</div>
	<div class="ma-banner">
		<div class="container-inner">
			<div class="row">
				
				<div class="col-md-3">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Hozmegamenu\Block\Menu')->setTemplate('Plazathemes_Hozmegamenu::verticalmegamenu.phtml')->toHtml();?>
				</div>
				<div class="col-md-9">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
				</div>
			</div>	
		</div>
	</div>
	
	<div class="container-inner">
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_home1')->toHtml(); ?>
	</div>
	<div class="group-products">
		<div class="container-inner">
			<div class="row">
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Newproductslider\Block\Newproductslider')->setTemplate('Plazathemes_Newproductslider::newproductslider.phtml')->toHtml();?>
				</div>
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Featureproductslider\Block\Featureproductslider')->setTemplate('Plazathemes_Featureproductslider::featureproductslider.phtml')->toHtml();?>
				</div>
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Randomproductslider\Block\Products')->setTemplate('Plazathemes_Randomproductslider::productslider.phtml')->toHtml();?>
				</div>
			</div>
		</div>
	</div>
	<?php echo $block->getLayout()->createBlock('Plazathemes\Bestsellerproduct\Block\Bestsellerproduct')->setTemplate('Plazathemes_Bestsellerproduct::bestsellerproduct.phtml')->toHtml();?>
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_home4')->toHtml(); ?>
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category_products1')->toHtml(); ?>
	<div class="group-block">
		<div class="container-inner">
			<div class="row">
				<div class="col-sm-4">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Pricecountdown\Block\Pricecountdown')->setTemplate('Plazathemes_Pricecountdown::saleslider.phtml')->toHtml();?>
				</div>
				<div class="col-sm-8">
					<?php echo $block->getLayout()->createBlock('Plazathemes\Categorytop\Block\Categorytop')->setTemplate('Plazathemes_Categorytop::categorytop.phtml')->toHtml();?>
				</div>
			</div>
		</div>
	</div>

	<div class="container-inner">
		<div class="row group-list">
			<div class="col-sm-4">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('about_us')->toHtml(); ?>
			</div>
			<div class="col-sm-4">
				<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('Plazathemes_Blog::sidebar/slider.phtml')->toHtml();?>
			</div>
			<div class="col-sm-4">
				<?php echo $block->getLayout()->createBlock('Plazathemes\LatestTweet\Block\LatestTweet')->setTemplate('Plazathemes_LatestTweet::latesttweet.phtml')->toHtml();?>
			</div>
		</div>
	</div>
</div>


