<div class="main-container">
	<?php echo $block->getLayout()->createBlock('Plazathemes\Bannerslider\Block\Bannerslider')->setTemplate('Plazathemes_Bannerslider::bannerslider.phtml')->toHtml();?>
	<div class="container-inner">
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('corporate_about')->toHtml(); ?>
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_home1')->toHtml(); ?>
	</div>
	<?php echo $block->getLayout()->createBlock('Plazathemes\Producttab\Block\Producttab')->setTemplate('Plazathemes_Producttab::producttab.phtml')->toHtml();?>
	<div class="container-inner">
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_home2')->toHtml(); ?>
	</div>
	<?php echo $block->getLayout()->createBlock('Plazathemes\Bestsellerproduct\Block\Bestsellerproduct')->setTemplate('Plazathemes_Bestsellerproduct::bestsellerproduct.phtml')->toHtml();?>
	<div class="container-inner">
		<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_home3')->toHtml(); ?>
	</div>
	<?php echo $block->getLayout()->createBlock('Plazathemes\Pricecountdown\Block\Pricecountdown')->setTemplate('Plazathemes_Pricecountdown::saleslider.phtml')->toHtml();?>
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('category_products1')->toHtml(); ?>
	
	<div class="container-inner">
		<div class="row group-list">
			<div class="col-sm-4">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('about_us')->toHtml(); ?>
			</div>
			<div class="col-sm-4">
				<?php echo $block->getLayout()->createBlock('Plazathemes\Blog\Block\Sidebar\Recent')->setTemplate('Plazathemes_Blog::sidebar/slider.phtml')->toHtml();?>
			</div>
			<div class="col-sm-4">
				<?php echo $block->getLayout()->createBlock('Plazathemes\LatestTweet\Block\LatestTweet')->setTemplate('Plazathemes_LatestTweet::latesttweet.phtml')->toHtml();?>
			</div>
		</div>
	</div>
	<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_home4')->toHtml(); ?>
	<?php echo $block->getLayout()->createBlock('Plazathemes\Testimonial\Block\Testimonial')->setTemplate('Plazathemes_Testimonial::testimonial.phtml')->toHtml();?>
</div>


