<?php 
	$enable = $block->getConfig('enabled');
	if($enable < 1) return ; 
	$items = $block->getConfig('items');
	$title = $block->getConfig('title'); 
	$speed = $block->getConfig('speed');
	$qty = $block->getConfig('qty');
	$showCart = 1;
	$showWishlist = 1;
	$showCompare = 1;
	$show_navigation = $block->getConfig('navigation');
	$show_pagination = $block->getConfig('pagination');
	$auto = $block->getConfig('auto');
	$rows = 3;
	
?>

<div class="featureproduct-slider">
		<div class='title'><h3><span><?php echo $title;?> </span></h3></div>
		<div class="feature-container">
				<?php 
				$newItems =  $block -> getFeaturedProduct()->getItems(); 
				$imageBlock =  $block->getLayout()->createBlock('Magento\Catalog\Block\Product\Image');
				$image = 'new_products_content_widget_grid';
				$type = 'widget-new-grid';
				$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
				$i = 0;
				foreach($newItems as $_item) { 
					$productImage = $block->getImage($_item, $image);
				?>
				<?php if($i++%$rows==0) { ?> <div class="products-grid"> <?php } ?>
						
						<div class="product-item">
							<div class="item-inner">
								<div class="product-item-info">	
									<div class=" product-item-images">
										<a href="<?php echo $block->getProductUrl($_item) ?>" class="product-item-photo">
											<?php echo $productImage->toHtml() ?>
										</a>
									</div>
									
												
									<div class="product-item-details">
										<strong class="product-item-name">
											<a title="<?php echo $block->escapeHtml($_item->getName()) ?>"
											   href="<?php echo $block->getProductUrl($_item) ?>"
											   class="product-item-link">
												<?php echo $block->escapeHtml($_item->getName()) ?>
											</a>
										</strong>
										<?php echo $block->getProductPrice($_item); ?>
										<?php echo $block->getReviewsSummaryHtml($_item, $templateType,true); ?>
										
									</div>	
								</div>	
							</div>
						</div>
					<?php if($i%$rows==0 || $i == count($newItems)) { ?> </div> <?php }?>
				<?php 
				}
				?>
		</div>
</div>
<script type="text/javascript">
require([
  "jquery",
  "owlcarousel/minjs"
 ], function($,owlCarousel){
	
   $(".feature-container").owlCarousel( {
		items : <?php if($items) { echo $items; } else { echo 5; }?>,
		autoPlay : <?php if($auto) echo 'true'; else echo 'false'; ?>,
		slideSpeed : <?php if($speed) echo $speed; else echo '500'; ?>,
		navigation : true,
		stopOnHover : true,
		pagination : <?php if($show_pagination) echo 'true'; else echo 'false'; ?>,
		items : 1,
		itemsDesktop : [1199,1],
		itemsDesktopSmall : [992,1],
		itemsTablet: [767,1],
		itemsMobile : [479,1]
   });
   
});
</script>   