<div class="footer-container">
	<div class="ma-brand">
		<div class="container-inner">
			<?php echo $block->getLayout()->createBlock('Plazathemes\Brandslider\Block\Brandslider')->setTemplate('Plazathemes_Brandslider::brandslider.phtml')->toHtml();?>
		</div>
	</div>
	<div class="footer-top">
		<div class="container-inner">
			<div class="container-size">
				<?php //echo $this->getChildHtml('footer_static')?>
				<div class="row">
					<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer_static')->toHtml();?>
				</div>
			</div>
			
		</div>
	</div>
	<div class="footer-bottom">
		<div class="text-center link_follow">
				<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('link_follow')->toHtml();?>
		</div>
		<div class="container-inner">
			<?php echo $this->getChildHtml('copyright')?>
			<?php echo $this->getChildHtml("store_switcher"); ?>
		</div>
		<div id="back_top">
			<a href="#back-top"></a>
		</div>
	</div>
</div>
<script type="text/javascript">
			
	require(["jquery"], function($){

	   $(window).scroll(function() {
			if($(this).scrollTop() > 300) {
				$('#back_top').fadeIn();   
			} else {
				$('#back_top').fadeOut();
			}
		});
		   $('#back_top').click(function() {
			$('body,html').animate({scrollTop:0},500);
		}); 
	   
	});
</script>